language: node_js
node_js:
- "7"

git:
  depth: 1

branches:
  only:
  - master

cache:
  directories:
  - "node_modules"
  yarn: true

install:
- npm install -g webpack

before_script:
- yarn install

script:
- yarn run coveralls
- yarn run build

